# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(979, 742)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        mainWindow.setAcceptDrops(False)
        mainWindow.setWindowOpacity(1.0)
        mainWindow.setAutoFillBackground(False)
        mainWindow.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(mainWindow)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.desktopTable = QtWidgets.QTableWidget(mainWindow)
        self.desktopTable.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desktopTable.sizePolicy().hasHeightForWidth())
        self.desktopTable.setSizePolicy(sizePolicy)
        self.desktopTable.setStyleSheet("")
        self.desktopTable.setLineWidth(20)
        self.desktopTable.setMidLineWidth(0)
        self.desktopTable.setAutoScroll(True)
        self.desktopTable.setAutoScrollMargin(16)
        self.desktopTable.setTextElideMode(QtCore.Qt.ElideRight)
        self.desktopTable.setObjectName("desktopTable")
        self.desktopTable.setColumnCount(0)
        self.desktopTable.setRowCount(0)
        self.desktopTable.horizontalHeader().setVisible(False)
        self.desktopTable.horizontalHeader().setDefaultSectionSize(80)
        self.desktopTable.horizontalHeader().setMinimumSectionSize(25)
        self.desktopTable.horizontalHeader().setSortIndicatorShown(False)
        self.desktopTable.verticalHeader().setVisible(False)
        self.desktopTable.verticalHeader().setDefaultSectionSize(60)
        self.horizontalLayout.addWidget(self.desktopTable)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
