# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qdesker.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Qdesker(object):
    def setupUi(self, Qdesker):
        Qdesker.setObjectName("Qdesker")
        Qdesker.resize(466, 356)
        Qdesker.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Qdesker.setAcceptDrops(True)
        Qdesker.setWindowOpacity(1.0)
        Qdesker.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(Qdesker)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 150, 75, 23))
        self.pushButton.setObjectName("pushButton")
        Qdesker.setCentralWidget(self.centralwidget)

        self.retranslateUi(Qdesker)
        QtCore.QMetaObject.connectSlotsByName(Qdesker)

    def retranslateUi(self, Qdesker):
        _translate = QtCore.QCoreApplication.translate
        Qdesker.setWindowTitle(_translate("Qdesker", "Qdesker"))
        self.pushButton.setText(_translate("Qdesker", "新建卡片"))
